### ISSUE TITLE
Latest version (4.24.2) fails with Octopus Deploy 2.6.4.951

### ISSUE THREAD

**Issue by anthonyangel** [OctopusDeploy/OctopusClients#200]
The latest version of octo.exe, installed as a nuget package won't deploy when using Server 2.6, I am getting the error `cannot resolve source` and the following

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Octopus.Cli.Commands.CreateReleaseCommand.<Execute>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Octopus.Cli.Commands.ApiCommand.<Execute>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Octopus.Cli.Program.Run(String[] args)
Exit code: -3
Running build failed.`

The same setup works with 4.24.1 and previous releases. I have pinned the version of the Nuget package for now

**Comment by benPearce1** [comment]
Hi @anthonyangel,

Sorry to hear the last version caused you some issues, we will have a fix out shortly.

Regards
Ben

**Comment by benPearce1** [comment]
Hi @anthonyangel, 

This issue has been resolved and is fixed in version 4.24.3 available on the downloads page.

Regards
Ben
