### ISSUE TITLE
docker octopusdeploy/octo System.ArgumentNullException: SafeHandle cannot be null.

### ISSUE THREAD

**Issue by spidduz** [OctopusDeploy/OctopusClients#255]
Hello
When I try to create-release with the following parameters:
docker run --rm -v $(pwd):/src octopusdeploy/octo create-release --project=PackageName --version=1.0.0 --package=PackageName:1.0.0 --ignoreexisting --server=http://serveroctopus/ --apiKey=API-apikey
returns: 
```
System.ArgumentNullException: SafeHandle cannot be null.
Parameter name: pHandle
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.Globalization.GetSortKey(SafeSortHandle sortHandle, String str, Int32 strLength, Byte* sortKey, Int32 sortKeyLength, CompareOptions options)
   at System.Globalization.CompareInfo.GetHashCodeOfStringCore(String source, CompareOptions options)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Octopus.Cli.Commands.Releases.PackageVersionResolver.Add(String stepName, String packageVersion) in Z:\buildAgent\workDir\52d4a5804c7de8e\source\Octopus.Cli\Commands\Releases\PackageVersionResolver.cs:line 93
   at Octopus.Cli.Commands.Releases.PackageVersionResolver.Add(String stepNameAndVersion) in Z:\buildAgent\workDir\52d4a5804c7de8e\source\Octopus.Cli\Commands\Releases\PackageVersionResolver.cs:line 77
   at Octopus.Cli.Infrastructure.Option.Invoke(OptionContext c) in Z:\buildAgent\workDir\52d4a5804c7de8e\source\Octopus.Cli\Infrastructure\Options.cs:line 492
   at Octopus.Cli.Infrastructure.OptionSet.Parse(String argument, OptionContext c) in Z:\buildAgent\workDir\52d4a5804c7de8e\source\Octopus.Cli\Infrastructure\Options.cs:line 833
   at Octopus.Cli.Infrastructure.OptionSet.<>c__DisplayClass22_0.<Parse>b__0(String argument) in Z:\buildAgent\workDir\52d4a5804c7de8e\source\Octopus.Cli\Infrastructure\Options.cs:line 742
   at System.Linq.Enumerable.WhereArrayIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Octopus.Cli.Infrastructure.OptionSet.Parse(IEnumerable`1 arguments) in Z:\buildAgent\workDir\52d4a5804c7de8e\source\Octopus.Cli\Infrastructure\Options.cs:line 740
   at Octopus.Cli.Infrastructure.Options.Parse(IEnumerable`1 arguments) in Z:\buildAgent\workDir\52d4a5804c7de8e\source\Octopus.Cli\Infrastructure\OptionGroup.cs:line 36
   at Octopus.Cli.Commands.ApiCommand.<Execute>d__36.MoveNext()
   at Octopus.Cli.CliProgram.Run(String[] args) in Z:\buildAgent\workDir\52d4a5804c7de8e\source\Octopus.Cli\CliProgram.cs:line 52
```

If I run the previous command on windows it works fine.
It seems that I can't use the parameter --package=PackageName:1.0.0 specifying the version number.
If I remove :1.0.0 it works.

**Comment by zentron** [comment]
Related to: https://github.com/dotnet/corefx/issues/28021

**Comment by zentron** [comment]
An updated Dockerfile was provided for this that takes effect from version `4.35.1`
